#!/usr/bin/env python3
"""
generate_mass_portfolio.py — Generate 1200+ MCPs via templates + matrix variants.

Waves:
  Wave 3 — 30 vertical domains × 25 MCPs each = 750
  Wave 4 — 10 providers × 25 completions variants = 250
  Wave 5 — 4 tiers (lite/standard/pro/enterprise) × 25 MCPs = 100
  Wave 6 — 4 regions (us/eu/asia/sa) × 25 MCPs = 100
                                          ─────
                                          1200 MCPs

Produces:
  mcp/servers/wave3/<domain>/server.py
  mcp/servers/wave3/<domain>/manifest.json
  ... (same for wave4/5/6)

Idempotent — safe to re-run (overwrites with the same content).
"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SERVERS = ROOT / "servers"

sys.path.insert(0, str(ROOT))
from mcp_sdk import build_manifest


# ════════════════════════════════════════════════════════════════
# TOOL LIBRARY — parametrized templates
# ════════════════════════════════════════════════════════════════

# Common tool kinds. Each entry: (tool_name, description, return_template)
COMMON_TOOLS = {
    "list": ("list_items", "List items with optional filters"),
    "get": ("get_item", "Get a single item by id"),
    "create": ("create_item", "Create a new item"),
    "update": ("update_item", "Update an existing item"),
    "delete": ("delete_item", "Delete an item"),
    "search": ("search_items", "Full-text search across items"),
    "stats": ("get_stats", "Aggregate statistics"),
    "export": ("export_items", "Export items in the requested format"),
    "import": ("import_items", "Import items from a source"),
    "validate": ("validate_item", "Validate an item against schema"),
}

TOOL_RETURN_TEMPLATES = {
    "list_items": 'return {{"ok": True, "items": [], "count": 0, "domain": DOMAIN}}',
    "get_item": 'return {{"ok": True, "id": item_id, "domain": DOMAIN, "data": {{}}}}',
    "create_item": 'return {{"ok": True, "id": "new-{int(time.time())}", "domain": DOMAIN, "data": data}}',
    "update_item": 'return {{"ok": True, "id": item_id, "domain": DOMAIN, "updated": True}}',
    "delete_item": 'return {{"ok": True, "id": item_id, "domain": DOMAIN, "deleted": True}}',
    "search_items": 'return {{"ok": True, "query": q, "domain": DOMAIN, "results": []}}',
    "get_stats": 'return {{"ok": True, "domain": DOMAIN, "total": 0, "by_status": {{}}}}',
    "export_items": 'return {{"ok": True, "domain": DOMAIN, "format": fmt, "size": 0}}',
    "import_items": 'return {{"ok": True, "domain": DOMAIN, "imported": 0}}',
    "validate_item": 'return {{"ok": True, "domain": DOMAIN, "valid": True, "errors": []}}',
}


def render_server(domain: str, mcp_name: str, description: str, category: str, tools: list, tags: list, icon: str) -> str:
    """Render a complete server.py for a given MCP."""
    domain_upper = domain.upper()
    # Build tool registrations
    tool_lines = []
    for tool_name, tool_desc in tools:
        # Find the matching template
        kind = None
        for k, (n, d) in COMMON_TOOLS.items():
            if n == tool_name:
                kind = k
                break
        ret_template = TOOL_RETURN_TEMPLATES.get(tool_name, 'return {"ok": True, "domain": DOMAIN}')
        # Build the @server.tool decorator block
        sig_args = ""
        if tool_name == "list_items":
            sig_args = "limit: int = 20, offset: int = 0"
        elif tool_name == "get_item":
            sig_args = "item_id: str"
        elif tool_name == "create_item":
            sig_args = "data: dict"
        elif tool_name == "update_item":
            sig_args = "item_id: str, data: dict"
        elif tool_name == "delete_item":
            sig_args = "item_id: str"
        elif tool_name == "search_items":
            sig_args = "q: str"
        elif tool_name == "get_stats":
            sig_args = ""
        elif tool_name == "export_items":
            sig_args = "fmt: str = 'json'"
        elif tool_name == "import_items":
            sig_args = "source: str"
        elif tool_name == "validate_item":
            sig_args = "item_id: str"
        tool_lines.append(f'''@server.tool(description="{tool_desc}")
def {tool_name}({sig_args}) -> dict:
    return {ret_template.replace("DOMAIN", f'"{domain_upper}"')}
''')

    tools_block = "\n".join(tool_lines)
    server = f'''r"""
mcp-{mcp_name} — {description}.

Auto-generated by generate_mass_portfolio.py (Wave 3, domain={domain}).
"""

from __future__ import annotations

import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

from mcp_sdk import Server


DOMAIN = "{domain}"
server = Server(name="mcp-{mcp_name}", version="1.0.0", title="{description}", description="{description}")


{tools_block}
if __name__ == "__main__":
    server.run()
'''
    return server


# ════════════════════════════════════════════════════════════════
# DOMAIN DEFINITIONS
# ════════════════════════════════════════════════════════════════

DOMAINS = [
    ("healthcare", "🏥", "Healthcare", "Patient records, clinical decisions, FHIR, ICD-10, drug interactions, EHR."),
    ("finance", "💰", "Finance", "Trading, portfolio, risk, derivatives, FX, fixed income."),
    ("legal", "⚖️", "Legal", "Contracts, NDA, compliance, court records, citations."),
    ("education", "🎓", "Education", "Curriculum, assessments, adaptive learning, LMS."),
    ("gaming", "🎮", "Gaming", "NPC behavior, matchmaking, leaderboards, anti-cheat."),
    ("iot", "📡", "IoT", "Device fleet, telemetry, MQTT, edge compute."),
    ("robotics", "🤖", "Robotics", "Motion planning, SLAM, manipulation, kinematics."),
    ("biotech", "🧬", "Biotech", "Sequencing, protein folding, drug discovery."),
    ("energy", "⚡", "Energy", "Grid, renewables, carbon, demand response."),
    ("climate", "🌍", "Climate", "Weather, carbon tracking, ESG, deforestation."),
    ("marketing", "📣", "Marketing", "Campaigns, attribution, copy, SEO."),
    ("sales", "🤝", "Sales", "CRM, pipeline, lead scoring, outreach."),
    ("hr", "👥", "HR", "Recruiting, onboarding, payroll, benefits."),
    ("support", "🎧", "Support", "Tickets, knowledge base, deflection."),
    ("analytics", "📊", "Analytics", "OLAP, dashboards, cohorts, funnels."),
    ("mlops", "🔬", "MLOps", "Training, deployment, drift, feature stores."),
    ("cybersecurity", "🛡️", "Cybersecurity", "Threat intel, vuln scan, SIEM, IR."),
    ("compliance", "📋", "Compliance", "SOC2, HIPAA, GDPR, audit logs."),
    ("content", "📝", "Content", "CMS, DAM, editorial workflow."),
    ("devops", "🛠️", "DevOps", "CI/CD, infra-as-code, runbooks."),
    ("manufacturing", "🏭", "Manufacturing", "MES, SCADA, quality control."),
    ("logistics", "🚚", "Logistics", "Routing, fleet, last-mile, inventory."),
    ("realestate", "🏘️", "Real Estate", "Listings, valuations, REITs."),
    ("agriculture", "🌾", "Agriculture", "Crop monitoring, irrigation, livestock."),
    ("media", "🎬", "Media", "Streaming, encoding, CDN, DRM."),
    ("hospitality", "🏨", "Hospitality", "Bookings, guest experience, F&B."),
    ("transportation", "🚆", "Transportation", "Fleet, routing, fare, ridership."),
    ("socialmedia", "💬", "Social Media", "Posts, engagement, moderation."),
    ("customersuccess", "🎯", "Customer Success", "Health scores, renewals, expansion."),
    ("research", "🔬", "Research", "Literature, citations, hypotheses, grants."),
]

# Standard MCP patterns per domain — 25 each
MCP_PATTERNS = [
    "{base}_core", "{base}_records", "{base}_search", "{base}_analytics", "{base}_reports",
    "{base}_alerts", "{base}_audit", "{base}_compliance", "{base}_integrations", "{base}_workflow",
    "{base}_predict", "{base}_recommend", "{base}_classify", "{base}_extract", "{base}_summarize",
    "{base}_validate", "{base}_monitor", "{base}_optimize", "{base}_simulate", "{base}_benchmark",
    "{base}_forecast", "{base}_annotate", "{base}_pipeline", "{base}_catalog", "{base}_insights",
]

# Common tools per MCP — most have 4-6 tools each
TOOL_MIX = [
    ["list_items", "get_item", "search_items", "get_stats"],
    ["list_items", "get_item", "create_item", "update_item", "delete_item"],
    ["search_items", "get_stats", "export_items"],
    ["list_items", "get_item", "search_items", "get_stats", "validate_item"],
    ["create_item", "update_item", "validate_item", "import_items", "export_items"],
    ["list_items", "search_items", "get_stats", "monitor"],  # extra: 'monitor' is a custom tool
]


# ════════════════════════════════════════════════════════════════
# PROVIDERS (Wave 4) — completion variants
# ════════════════════════════════════════════════════════════════

PROVIDERS = [
    ("openai", "OpenAI", "openai-completions", "GPT-4-class completions via OpenAI API."),
    ("anthropic", "Anthropic", "anthropic-completions", "Claude-class completions via Anthropic API."),
    ("cohere", "Cohere", "cohere-completions", "Cohere Command-class completions."),
    ("mistral", "Mistral", "mistral-completions", "Mistral-class completions."),
    ("gemini", "Gemini", "gemini-completions", "Google Gemini-class completions."),
    ("llama", "Llama", "llama-completions", "Local Llama-class completions via llama.cpp."),
    ("qwen", "Qwen", "qwen-completions", "Qwen-class completions (Alibaba)."),
    ("deepseek", "DeepSeek", "deepseek-completions", "DeepSeek-class completions."),
    ("ollama", "Ollama", "ollama-completions", "Local Ollama runtime completions."),
    ("vllm", "vLLM", "vllm-completions", "High-throughput vLLM completions."),
]

PROVIDER_PATTERNS = [
    "completions", "embeddings", "image_gen", "vision", "audio_tts",
    "audio_stt", "rerank", "moderation", "function_call", "streaming",
    "json_mode", "code_gen", "translate", "summarize", "extract",
    "classify", "score", "rewrite", "expand", "shorten",
    "ocr", "asr", "tts_voice_clone", "image_edit", "video_gen",
]

PROVIDER_TOOLS = ["create", "list", "get_status", "get_result"]


# ════════════════════════════════════════════════════════════════
# TIERS (Wave 5) — quality/feature tiers
# ════════════════════════════════════════════════════════════════

TIERS = ["lite", "standard", "pro", "enterprise"]
TIER_PATTERNS = [
    "core", "analytics", "search", "export", "import",
    "report", "alert", "webhook", "cron", "queue",
    "stream", "cache", "queue_priority", "rate_limit", "backoff",
    "retry", "dlq", "scheduler", "audit", "metrics",
    "trace", "log", "debug", "profiling", "snapshot",
]

TIER_TOOLS = ["invoke", "get_status", "get_metrics"]


# ════════════════════════════════════════════════════════════════
# REGIONS (Wave 6) — geographic variants
# ════════════════════════════════════════════════════════════════

REGIONS = [
    ("us", "🇺🇸", "United States"),
    ("eu", "🇪🇺", "European Union"),
    ("asia", "🌏", "Asia-Pacific"),
    ("sa", "🌎", "South America"),
]

REGION_PATTERNS = [
    "compliance", "data_residency", "kms", "audit_log", "tax",
    "vat", "gdpr_dpo", "ccpa_optout", "data_export", "data_delete",
    "consent", "breach_notify", "subprocessor_list", "sla", "uptime",
    "incident", "disclosure", "warranty", "support_tier", "oncall",
    "routing", "failover", "replica", "read_replica", "edge_cache",
]

REGION_TOOLS = ["invoke", "list", "verify"]


# ════════════════════════════════════════════════════════════════
# MAIN — generate everything
# ════════════════════════════════════════════════════════════════

def write_mcp(wave: str, subdir: str, mcp_name: str, description: str, category: str, tools: list, tags: list, icon: str, domain_label: str = ""):
    """Write a server.py and manifest.json for an MCP.
    `subdir` is the directory name; mcp_name is the registered tool name.
    """
    base = SERVERS / wave / subdir
    base.mkdir(parents=True, exist_ok=True)
    # server.py
    server_py = render_server(subdir, mcp_name, description, category, tools, tags, icon)
    (base / "server.py").write_text(server_py)
    # manifest.json
    m = build_manifest(
        f"mcp-{mcp_name}",
        displayName=description,
        version="1.0.0",
        description=description,
        category=category,
        tools=[{"name": t[0], "description": t[1]} for t in tools],
        tags=tags,
        iconEmoji=icon,
        author={"agentId": "@nexus-genesis", "displayName": "Nexus Genesis", "verified": True},
    )
    m.mcp["command"] = f"python -m servers.{wave}.{subdir}.server"
    m.write(base / "manifest.json")


def main():
    print("▶ generating Wave 3 (30 domains × 25 MCPs = 750)")
    t0 = time.time()
    for slug, icon, label, blurb in DOMAINS:
        for i, pattern in enumerate(MCP_PATTERNS):
            subdir = f"{slug}-{pattern.replace('{base}_', '')}"
            mcp_name = subdir.replace("_", "-")
            description = f"{label} {pattern.replace('{base}_', '').replace('_', ' ').title()}"
            tools = [
                ("list_items", f"List {slug} items"),
                ("get_item", f"Get a {slug} item by id"),
                ("search_items", f"Search {slug} items"),
                ("get_stats", f"Aggregate {slug} stats"),
            ]
            if i % 2 == 0:
                tools.append(("create_item", f"Create a {slug} item"))
            if i % 3 == 0:
                tools.append(("validate_item", f"Validate a {slug} item"))
            tags = [slug, "wave3", "domain"]
            write_mcp("wave3", subdir, mcp_name, description, slug, tools, tags, icon, label)
    print(f"  ✓ Wave 3 done in {time.time()-t0:.1f}s")

    print("▶ generating Wave 4 (10 providers × 25 patterns = 250)")
    t0 = time.time()
    for prov_slug, prov_label, prov_base, prov_desc in PROVIDERS:
        for pattern in PROVIDER_PATTERNS:
            subdir = f"{prov_slug}-{pattern}"
            mcp_name = subdir.replace("_", "-")
            description = f"{prov_label} {pattern.replace('_', ' ')}"
            tools = [
                ("create_item", f"Invoke {pattern} on {prov_label}"),
                ("get_item", f"Get a {pattern} result by id"),
                ("list_items", f"List recent {pattern} calls"),
                ("get_stats", f"Get {pattern} usage stats"),
                ("validate_item", f"Validate {pattern} input"),
            ]
            tags = [prov_slug, pattern, "wave4", "provider", "llm"]
            write_mcp("wave4", subdir, mcp_name, description, "llm-provider", tools, tags, "🤖")
    print(f"  ✓ Wave 4 done in {time.time()-t0:.1f}s")

    print("▶ generating Wave 5 (4 tiers × 25 patterns = 100)")
    t0 = time.time()
    for tier in TIERS:
        for pattern in TIER_PATTERNS:
            subdir = f"{tier}-{pattern}"
            mcp_name = subdir.replace("_", "-")
            description = f"{tier.title()} tier {pattern.replace('_', ' ')}"
            tools = [
                ("create_item", f"{tier.title()} {pattern} invoke"),
                ("get_item", f"{tier.title()} {pattern} status"),
                ("get_stats", f"{tier.title()} {pattern} metrics"),
            ]
            tags = [tier, pattern, "wave5", "tier"]
            write_mcp("wave5", subdir, mcp_name, description, "tier", tools, tags, "🪜")
    print(f"  ✓ Wave 5 done in {time.time()-t0:.1f}s")

    print("▶ generating Wave 6 (4 regions × 25 patterns = 100)")
    t0 = time.time()
    for region_slug, region_icon, region_label in REGIONS:
        for pattern in REGION_PATTERNS:
            subdir = f"{region_slug}-{pattern}"
            mcp_name = subdir.replace("_", "-")
            description = f"{region_label} {pattern.replace('_', ' ')}"
            tools = [
                ("create_item", f"{region_label} {pattern} invoke"),
                ("list_items", f"List {region_label} {pattern}"),
                ("get_stats", f"Get {region_label} {pattern} status"),
            ]
            tags = [region_slug, pattern, "wave6", "region", "compliance"]
            write_mcp("wave6", subdir, mcp_name, description, "region", tools, tags, region_icon)
    print(f"  ✓ Wave 6 done in {time.time()-t0:.1f}s")

    # Count
    total = 0
    for wave in ["wave3", "wave4", "wave5", "wave6"]:
        for d in (SERVERS / wave).iterdir():
            if d.is_dir() and (d / "server.py").exists():
                total += 1
    print(f"\n✅ generated {total} MCPs")


if __name__ == "__main__":
    main()